- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Asterisk
  - Core
  - Edge
  - Glacier
  - Hammurabi
  - Lighthouse
  - Pebble
  - Saltern
  - Shoukou
  - Submarine
  - Tortuga
  - TheHive
  - Gax
  - Rad
  - Meta
  #- Europa
